import 'package:rent_car/model/car_model.dart';

List<CarModel> carList = [
  CarModel(
    company: "Ferrari",
    model: "Purosangue",
    image: "assets/images/purosangue.png",
    rating: 4.9,
    price: 428,
    maxSpeed: "310Km/h",
    engine: "V12 65°",
    ability: "4 Seats",
    airbag: "6",
    fuelType: "Petrol",
    drivetrain: "AWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Roma",
    image: "assets/images/360_modena.png",
    rating: 4.8,
    price: 395,
    maxSpeed: "320Km/h",
    engine: "V8 Turbo",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "F8 Tributo",
    image: "assets/images/296_gtb.png",
    rating: 4.9,
    price: 510,
    maxSpeed: "340Km/h",
    engine: "V8 Twin-T",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "SF90 Stradale",
    image: "assets/images/sf90.png",
    rating: 5.0,
    price: 690,
    maxSpeed: "340Km/h",
    engine: "V8 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "PHEV",
    drivetrain: "AWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "812 Superfast",
    image: "assets/images/812_superfast.png",
    rating: 4.8,
    price: 620,
    maxSpeed: "340Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "296 GTB",
    image: "assets/images/296_gtb.png",
    rating: 4.9,
    price: 575,
    maxSpeed: "330Km/h",
    engine: "V6 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "PHEV",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Daytona SP3",
    image: "assets/images/daytona_sp3.png",
    rating: 5.0,
    price: 920,
    maxSpeed: "340Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "LaFerrari",
    image: "assets/images/laferrari.png",
    rating: 5.0,
    price: 1200,
    maxSpeed: "350Km/h",
    engine: "V12 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Hybrid",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Portofino M",
    image: "assets/images/portofino_m.png",
    rating: 4.7,
    price: 360,
    maxSpeed: "320Km/h",
    engine: "3.9L V8",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "488 GTB",
    image: "assets/images/488_gtb.png",
    rating: 4.8,
    price: 465,
    maxSpeed: "330Km/h",
    engine: "3.9L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "488 Pista",
    image: "assets/images/488_pista.png",
    rating: 4.9,
    price: 540,
    maxSpeed: "340Km/h",
    engine: "3.9L V8 Twin",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "458 Italia",
    image: "assets/images/458_italia.png",
    rating: 4.8,
    price: 440,
    maxSpeed: "325Km/h",
    engine: "4.5L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "California T",
    image: "assets/images/california.png",
    rating: 4.6,
    price: 310,
    maxSpeed: "315Km/h",
    engine: "3.9L V8",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "GTC4Lusso",
    image: "assets/images/gtc4lusso.png",
    rating: 4.7,
    price: 470,
    maxSpeed: "335Km/h",
    engine: "6.3L V12",
    ability: "4 Seats",
    airbag: "6",
    fuelType: "Petrol",
    drivetrain: "AWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Monza SP2",
    image: "assets/images/monza_sp2.png",
    rating: 5.0,
    price: 980,
    maxSpeed: "300Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "599 GTB Fiorano",
    image: "assets/images/599_gtb.png",
    rating: 4.7,
    price: 390,
    maxSpeed: "330Km/h",
    engine: "6.0L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "F430 Spider",
    image: "assets/images/f430_spider.png",
    rating: 4.6,
    price: 350,
    maxSpeed: "310Km/h",
    engine: "4.3L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "360 Modena",
    image: "assets/images/360_modena.png",
    rating: 4.5,
    price: 295,
    maxSpeed: "295Km/h",
    engine: "3.6L V8",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Enzo Ferrari",
    image: "assets/images/f430_spider.png",
    rating: 5.0,
    price: 1500,
    maxSpeed: "350Km/h",
    engine: "6.0L V12",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
  CarModel(
    company: "Ferrari",
    model: "Testarossa",
    image: "assets/images/testarossa.png",
    rating: 4.8,
    price: 410,
    maxSpeed: "290Km/h",
    engine: "4.9L Flat-12",
    ability: "2 Seats",
    airbag: "0",
    fuelType: "Petrol",
    drivetrain: "RWD",
  ),
];