import 'package:rent_car/model/car_model.dart';

/// The Ferrari fleet. Image paths are verified against `assets/images/`.
List<CarModel> carList = [
  CarModel(
    company: "Ferrari",
    model: "Purosangue",
    image: "assets/images/purosangue.png",
    rating: 4.9,
    price: 428,
    maxSpeed: "310Km/h",
    engine: "V12 65°",
    ability: "4 Seats",
    airbag: "6",
    fuelType: "Petrol",
    drivetrain: "AWD",
    mileage: "12,400 km",
    category: CarCategory.suv,
    tagline: "The first ever four-door four-seater from Maranello.",
    gallery: ["assets/images/gtc4lusso.png", "assets/images/roma.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "Roma",
    image: "assets/images/roma.png",
    rating: 4.8,
    price: 395,
    maxSpeed: "320Km/h",
    engine: "V8 Turbo",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "8,700 km",
    category: CarCategory.coupe,
    tagline: "La Nuova Dolce Vita - timeless mid-front V8 elegance.",
    gallery: ["assets/images/portofino_m.png", "assets/images/california.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "F8 Tributo",
    image: "assets/images/f8_tributo.png",
    rating: 4.9,
    price: 510,
    maxSpeed: "340Km/h",
    engine: "V8 Twin-T",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "5,300 km",
    category: CarCategory.coupe,
    tagline: "A tribute to the most powerful V8 in Ferrari history.",
    gallery: ["assets/images/488_pista.png", "assets/images/488_gtb.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "SF90 Stradale",
    image: "assets/images/sf90.png",
    rating: 5.0,
    price: 690,
    maxSpeed: "340Km/h",
    engine: "V8 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "PHEV",
    drivetrain: "AWD",
    mileage: "3,150 km",
    category: CarCategory.hyper,
    tagline: "986 hp of plug-in hybrid fury with all-wheel drive.",
    gallery: ["assets/images/296_gtb.png", "assets/images/laferrari.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "812 Superfast",
    image: "assets/images/812_superfast.png",
    rating: 4.8,
    price: 620,
    maxSpeed: "340Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "6,900 km",
    category: CarCategory.coupe,
    tagline: "The naturally aspirated V12 flagship, 800 hp of theatre.",
    gallery: ["assets/images/599_gtb.png", "assets/images/gtc4lusso.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "296 GTB",
    image: "assets/images/296_gtb.png",
    rating: 4.9,
    price: 575,
    maxSpeed: "330Km/h",
    engine: "V6 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "PHEV",
    drivetrain: "RWD",
    mileage: "4,180 km",
    category: CarCategory.coupe,
    tagline: "The littlest Ferrari V6, reinvented with electric boost.",
    gallery: ["assets/images/sf90.png", "assets/images/f8_tributo.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "Daytona SP3",
    image: "assets/images/daytona_sp3.png",
    rating: 5.0,
    price: 920,
    maxSpeed: "340Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "1,250 km",
    category: CarCategory.hyper,
    tagline: "A homage to the 1967 Daytona 1-2-3 finish. Icona series.",
  ),
  CarModel(
    company: "Ferrari",
    model: "LaFerrari",
    image: "assets/images/laferrari.png",
    rating: 5.0,
    price: 1200,
    maxSpeed: "350Km/h",
    engine: "V12 Hybrid",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Hybrid",
    drivetrain: "RWD",
    mileage: "940 km",
    category: CarCategory.hyper,
    tagline: "The definitive hybrid hypercar. 949 hp, 499 built.",
  ),
  CarModel(
    company: "Ferrari",
    model: "Portofino M",
    image: "assets/images/portofino_m.png",
    rating: 4.7,
    price: 360,
    maxSpeed: "320Km/h",
    engine: "3.9L V8",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "10,400 km",
    category: CarCategory.convertible,
    tagline: "A retractable hard-top GT that does everything well.",
  ),
  CarModel(
    company: "Ferrari",
    model: "488 GTB",
    image: "assets/images/488_gtb.png",
    rating: 4.8,
    price: 465,
    maxSpeed: "330Km/h",
    engine: "3.9L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "7,300 km",
    category: CarCategory.coupe,
    tagline: "Twin-turbo V8 that rewrote the mid-engine rulebook.",
    gallery: ["assets/images/488_pista.png", "assets/images/f8_tributo.png"],
  ),
  CarModel(
    company: "Ferrari",
    model: "488 Pista",
    image: "assets/images/488_pista.png",
    rating: 4.9,
    price: 540,
    maxSpeed: "340Km/h",
    engine: "3.9L V8 Twin",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "6,500 km",
    category: CarCategory.coupe,
    tagline: "Track-honed special with the most powerful V8 yet.",
  ),
  CarModel(
    company: "Ferrari",
    model: "458 Italia",
    image: "assets/images/458_italia.png",
    rating: 4.8,
    price: 440,
    maxSpeed: "325Km/h",
    engine: "4.5L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "15,200 km",
    category: CarCategory.coupe,
    tagline: "The last naturally aspirated mid-engine V8 berlinetta.",
  ),
  CarModel(
    company: "Ferrari",
    model: "California T",
    image: "assets/images/california.png",
    rating: 4.6,
    price: 310,
    maxSpeed: "315Km/h",
    engine: "3.9L V8",
    ability: "4 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "17,800 km",
    category: CarCategory.convertible,
    tagline: "Grand touring comfort with a folding hard top.",
  ),
  CarModel(
    company: "Ferrari",
    model: "GTC4Lusso",
    image: "assets/images/gtc4lusso.png",
    rating: 4.7,
    price: 470,
    maxSpeed: "335Km/h",
    engine: "6.3L V12",
    ability: "4 Seats",
    airbag: "6",
    fuelType: "Petrol",
    drivetrain: "AWD",
    mileage: "9,600 km",
    category: CarCategory.suv,
    tagline: "A shooting brake V12 with room for four and their luggage.",
  ),
  CarModel(
    company: "Ferrari",
    model: "Monza SP2",
    image: "assets/images/monza_sp2.png",
    rating: 5.0,
    price: 980,
    maxSpeed: "300Km/h",
    engine: "6.5L V12",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "620 km",
    category: CarCategory.hyper,
    tagline: "A barchetta with no roof and no windscreen. Pure sensation.",
  ),
  CarModel(
    company: "Ferrari",
    model: "599 GTB Fiorano",
    image: "assets/images/599_gtb.png",
    rating: 4.7,
    price: 390,
    maxSpeed: "330Km/h",
    engine: "6.0L V12",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "22,400 km",
    category: CarCategory.coupe,
    tagline: "Front-mid V12 grand tourer derived from the Enzo.",
  ),
  CarModel(
    company: "Ferrari",
    model: "F430 Spider",
    image: "assets/images/f430_spider.png",
    rating: 4.6,
    price: 350,
    maxSpeed: "310Km/h",
    engine: "4.3L V8",
    ability: "2 Seats",
    airbag: "4",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "28,600 km",
    category: CarCategory.convertible,
    tagline: "Open-air V8 scream with the classic gated manual option.",
  ),
  CarModel(
    company: "Ferrari",
    model: "360 Modena",
    image: "assets/images/360_modena.png",
    rating: 4.5,
    price: 295,
    maxSpeed: "295Km/h",
    engine: "3.6L V8",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "34,200 km",
    category: CarCategory.coupe,
    tagline: "The aluminium-chassis V8 that started the modern era.",
  ),
  CarModel(
    company: "Ferrari",
    model: "Enzo Ferrari",
    image: "assets/images/enzo.png",
    rating: 5.0,
    price: 1500,
    maxSpeed: "350Km/h",
    engine: "6.0L V12",
    ability: "2 Seats",
    airbag: "2",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "38,100 km",
    category: CarCategory.hyper,
    tagline: "Formula 1 technology for the road. Only 400 ever made.",
  ),
  CarModel(
    company: "Ferrari",
    model: "Testarossa",
    image: "assets/images/testarossa.png",
    rating: 4.8,
    price: 410,
    maxSpeed: "290Km/h",
    engine: "4.9L Flat-12",
    ability: "2 Seats",
    airbag: "0",
    fuelType: "Petrol",
    drivetrain: "RWD",
    mileage: "46,900 km",
    category: CarCategory.coupe,
    tagline: "The 80s icon with the most recognisable side strakes ever.",
  ),
];
